# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b14c29970281331a7fe162a36e4abbe133eb87a2e7ada72e85124125af6d027c8591b450b041c00263d6fb1b327e3f47ceb7d272afa972c976f85fe0791d7264

test:
  secret_key_base: 5f471633c8d6b673e679539cdb46b30d0f4243674b32fd61918dc3899e7ee74e02241582262e556ed9f4fbd6d8d76d933eebe623ddd7104c77c760c43fc233cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
